# fly.toml app configuration file generated for abc-c6f54b79-79fd-49a1-b8a5-284e9fa7700d-server on 2024-06-19T09:27:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abc-c6f54b79-79fd-49a1-b8a5-284e9fa7700d-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
